export default {
    A: {
        Abacate   : 'Авокадо'     , Abacaxi      : 'Ананас'       , Abaixo     : 'Под'       , Abaixar     : 'Опускать', Abandonar  : 'Оставлять'  , 
        Aberto    : 'Открытый'    , Abismo       : 'Бездна'       , Abril      : 'Апрель'    , Acima       : 'Над'     , Acrescentar: 'Добавить'   , 
        Adeus     : 'До свидания' , Administrador: 'Администратор', Adoecer    : 'Заболеть'  , Adormecer   : 'Заснуть' , Adulto     : 'Взрослый'   , 
        Aeroporto : 'Аэропорт'    , Agosto       : 'Август'       , Agradecer  : 'Благдарить', Água        : 'Вода'    , Ajuda      : 'Помощь'     , 
        Alcançar  : 'Достать'     , Alegrar      : 'Радовать'     , Alegremente: 'Всело'     , Além        : 'Дальше'  , Alemanha   : 'Германия'   , 
        Algo      : 'Что-нибудь'  , Ali          : 'Там'          , Alimentar  : 'Кормить'   , Amarelo     : 'жёлтый'  , Amigo      : 'Друг'       , 
        Amizade   : 'Дружба'      , Aparecer     : 'Появиться'    , Aprender   : 'Учить'     , Aquele      : 'Тот'     , Aqui       : 'Тут / здесь', 
        Arremessar: 'Бросить'     , Arroz        : 'Рис'          , Arquiteto  : 'Архитектор', Assim       : 'Так'     , Atacar     : 'Ударить'    , 
        Avô       : 'Дедушка'     , Avó          : 'Бабушка'      , Azul       : 'Синий'     , 'Azul claro': 'Голубой' ,
    },
    B: {
        Baixo : 'Короткий', Balançar: 'Качать' , Banco : 'Банк'    , Banheiro  : 'Ванная комната'      , Banquisa: 'Льдина'    , Bar   : 'Бар'     , 
        Bebida: 'Напиток' , Barba   : 'Борода' , Barco : 'Корабль' , Básico    : 'Основной'            , Bastante: 'Достаточно', Batata: 'Картошка',
        Bebê  : 'Младенец', Beber   : 'Пить'   , Bem   : 'Хорошо'  , Biblioteca: 'Библиотека'          , Bola    : 'Мяч'       , Bonito: 'Красивый', 
        Botas : 'Ботинки' , Branco  : 'Белый'  , Brasil: 'Бразилия', Brasileiro: 'Бразилец/бразильский', Buraco  : 'Дырка'     , Buscar: 'Искать'  ,
    },
    C: {
        Cabeça  : 'Голова'    , Cabelo            : 'Волос'        , Caçar           : 'Ловить'    , Cachecol: 'Шарф'     , Cachorro : 'Собака'    , 
        Cadeira : 'Стул'      , Café              : 'Кофе'         , Canadá          : 'Канада'    , Caneta  : 'Ручка'    , Chapéu   : 'Шляпа'     , 
        Cair    : 'Выпасть'   , 'Caixa eletrônico': 'Банкомат'     , Cama            : 'Кровать'   , Caminhar: 'Ходить'   , Cardápio : 'Меню'      , 
        Carne   : 'Мясо'      , 'Carne bovina'    : 'Говядина'     , 'Carne de porco': 'Свинина'   , Carro   : 'Машина'   , Carteira : 'Бумажник'  , 
        Casa    : 'Дом'       , Casaco            : 'Пальто'       , Cazaquistão     : 'Казахстан' , Cebola  : 'Лук'      , Centro   : 'Центр'     , 
        Certo   : 'Правильный', Cerveja           : 'Пиво'         , Chá             : 'Чай'       , Chamada : 'Вызов'    , Chamar   : 'Звать'     , 
        Chatear : 'Наскучить' , Chorar            : 'Плакать'      , China           : 'Китай'     , Cidade  : 'Город'    , Cinco    : 'Пять'      , 
        Cinza   : 'Серый'     , Cliente           : 'Клиент'       , Cobrir          : 'Накрывать' , Coisa   : 'Вещь'     , Coleção  : 'Подборка'  , 
        Colega  : 'Коллега'   , Colher            : 'Ложка (subst)', Comer           : 'Есть'      , Comida  : 'Еда'      , Como     : 'Как'       , 
        Compra  : 'Покупка'   , Comprar           : 'Купить'       , Confundir       : 'Спутать'   , Conhecer: 'Встречать', Conseguir: 'Достичь'   , 
        Congelar: 'Замерзнуть', Considerar        : 'Рассмотреть'  , Consumidor      : 'Покупатель', Conta   : 'Счёт'     , Continuar: 'Продолжать', 
        Contra  : 'Против'    , Copo              : 'Стакан'       , Cor             : 'Цвет'      , Coração : 'Сердце'   , Coreia   : 'Корея'     , 
        Cortar  : 'Нарезать'  , Crescer           : 'Расти'        , Criança         : 'Ребёнок'   , Crianças: 'Дети'     , Cotovelo : 'Локоть'    , 
        Costela : 'Ребро'     , Cozinha           : 'Кухня'        , Cume            : 'Вершина'   ,
    },
    D: {
        Daqui   : 'Отсюда'      , De       : 'Из'           , Debaixo     : 'Под'        , Definitivamente: 'Определённо', Delicioso: 'Вкусный'     , 
        Demais  : 'Слишком'     , 'De fato': 'Именно'       , 'De repente': 'Вдруг'      , 'De onde'      : 'Откуда'     , Derrotado: 'Побеждённый' , 
        Desgraça: 'Бедa'        , Despedir : 'Прощать'      , Dez         : 'Десять'     , Dezembro       : 'Декабрь'    , Dezoito  : 'Восемнадцать', 
        Dezenove: 'Девятнадцать', Dezesseis: 'Шестнадцать'  , Dezessete   : 'Семнадцать' , Dicionário     : 'Словарь'    , Dizer    : 'Сказать'     , 
        Dois    : 'Два'         , Doente   : 'Больной/болен', Domingo     : 'Воскресенье', Doze           : 'Двенадцать' , Durante  : 'В течение'   ,
    },
    E: {
        E       : 'И'      , 'É claro': 'Конечно'       , Economia  : 'Экономика', Egito   : 'Египет'  , Ela          : 'Она'     , Ele    : 'Он'       ,
        Eles    : 'Они'    , Em       : 'В / на'        , Endereço  : 'Адрес'    , Entender: 'Понимать', Errado       : 'Неправый', Escócia: 'Шотландия',
        Escola  : 'Школа'  , Escrever : 'Писать'        , Escritório: 'Офис'     , Escuro  : 'Тёмный'  , Especialmente: 'Особенно', Esporte: 'Спорт'    , 
        Espanha : 'Испания', Esposa   : 'жeнa'          , Estádio   : 'Стадион'  , Estação : 'Станция' , Estante      : 'Шкаф'    , Este   : 'Этот'     , 
        Estômago: 'желудок', Evidência: 'Доказательство', Evitar    : 'Избегать' , Eu      : 'Я'       , Exatamente   : 'Точно'   ,
    },
    F: {
        Fábrica   : 'Завод'      , Faca     : 'Нож'    , Falar   : 'Говорить', Falso  : 'Неверный(ая)', Faminto: 'Голодный', Família: 'Семья'      ,
        Fantástico: 'Потрясающий', Farmácia : 'Аптека' , Favorito: 'Любимый' , Fazenda: 'Ферма'       , Fechado: 'Закрытый', Feio   : 'Некрасивый' ,
        Feliz     : 'Счастливый' , Fevereiro: 'Февраль', Ficar   : 'Остаться', Filha  : 'Дочь'        , Filho  : 'Сын'     , Fino   :     'Тонкий' ,
        Forte     : 'Сильный'    , Fraco    : 'Слабый' , França  : 'Франция' , Frango : 'Курица'      , Fruta  : 'Фрукт'
    },
    G: {
        Ganhar        : 'Выиграть', Garçom: 'Официант' , Garçonete: 'Официантка' , Garfo  : 'Вилка', Garganta: 'Горло / глотка', Garrafa: 'Бутылка',
        Garota        : 'Девочка ', Garoto: 'Мальчик ' , Gato     : 'Кот / Кошка', Gênio  : 'Гений', Genitor : 'Родитель'      , Gordo  : 'Толстый', 
        Gorro         : 'Шапка'   , Gostar: 'Нравиться', Grande   : 'Большой'    , Gramado: 'Газон', Gravata : 'Галстук'       , Grito  : 'Крик'   , 
        'Guarda-chuva': 'Зонт'    ,
    },
    H: {
        Homem: 'Мужчина', Hora: 'Час', Hospital: 'Больница'
    },
    I: {
        Imaginação: 'Воображение', Inglês: 'Английский', Índia: 'Индия', Infecção: 'Инфекция', Inferno: 'Ад'    , Insanamente: 'Безумно',
        Injusto   : 'Нечестный'  , Irmã  : 'Сестра'    , Irmão: 'Брат' , Irritado: 'Злой'    , Irritar: 'Бесить', Isso       : 'Оно'    , 
        Itália    : 'Италия'     ,
    },
    J: {
        Janeiro: 'Январь', Jantar: 'Ужинать (verbo)', Jaqueta: 'Пиджак', Japão: 'Япония', Joelho: 'Колень', Jogo: 'Игра', Jogar: 'Играть',
        Junho  : 'Июнь'  , Julho : 'Июль'           ,
    },
    L: {
        Laranja : 'Апельсин', Laranjado: 'Оранжевый', Legal   : 'Классный'       , Legume: 'Овощ' , Leite: 'Молоко', Lembrar: 'Вспоминать', 
        Levantar: 'Вставать', Ligar    : 'Включать' , Livraria: 'Книжный магазин', Livro : 'Книга', Limão: 'Лимон' , Longo  : 'Длинный'   , 
        Loja    : 'Магазин' , Luvas    : 'Перчатки' ,
    },
    M: {
        Mãe   : 'Мать'    , Macarrão: 'Макароны'  , Maçã : 'Яблоко'    , Magro      : 'Худой'   , Maio            : 'Май'        , 
        Maior : 'Побольше', Manteiga: 'Масло'     , Março: 'Март'      , Maravilhoso: 'Чудесный', Maravilhosamente: 'Чудесно'    , 
        Marido: 'Муж'     , Marrom  : 'Коричневый', Matar: 'Убить'     , Meias      : 'Носки'   , Melhorar        : 'Поправиться', 
        Menor : 'Поменьше', Mercado : 'Рынок'     , Merda: 'Гавно(adj)', Mesa       : 'Стол'    , Mexer           : 'Двигаться'  , 
        Molho : 'Соус'    , Mudar   : 'Изменить'  , Muito: 'Очень'     , Mulher     : 'Женщина' ,
    },
    N: {
        Não         : 'Не / нет' , Nada      : 'Ничего'    , Namorada: 'Девушка', Naturalmente: 'Естественно'   , Nativo  : 'Местный', 
        'Na verdade': 'Вообще-то', Necessário: 'Необходимо', Ninguém : 'Никто'  , Nojento     : 'Отвратительный', Nome    : 'Имя'    , 
        Normal      : 'Нормально', Noruega   : 'Норвегия'  , Nós     : 'Мы'     , Nove        : 'Девять'        , Novembro: 'Ноябрь' , 
        Novo        : 'Новый'    , Número    : 'Номер'     ,
    },
    O: {
        Obrigado: 'Спасибо', Observar: 'Наблюдать'  , Oferecer: 'Предложить', Oi    : 'Привет(informal)', Oito   : 'Восемь', Onde : 'Где'  ,
        Ônibus  : 'Автобус', Onze    : 'Одиннадцать', Oops    : 'Ой'        , Opinar: 'Высказать'       , Opinião: 'Мнение', Ordem: 'Приказ', 
        Ovo     : 'Яйцо'   , Ou      : 'Или'        , Outubro : 'Октябрь'   , Ombro : 'Плечо'           ,
    },
    P: {
        Pão        : 'Хлеб'      , Pagar   : 'Платить'    , Pai     : 'Отец'     , Parar : 'Остановить(ся)', Papel   : 'Бумага'       , 
        Parque     : 'Парк'      , Pedir   : 'Заказывать' , Pegar   : 'Брать'    , Peito : 'Грудь'         , Peixe   : 'Рыба'         , 
        Pele       : 'Кожа'      , Pensar  : 'Думать'     , Perceber: 'Проводить', Perder: 'Проиграть'     , Perfeito: 'Идеальный'    ,
        Pernoitar  : 'Ночевать'  , Perto   : 'Возле/Рядом', Pescador: 'Рыбак'    , Pessoa: 'Человек'       , Pessoas : 'Люди'         , 
        Pequeno    : 'Маленький' , Piscina : 'Бассейн'    , Poeta   : 'Поэт'     , Ponte : 'Мост'          , Por     : 'За'           , 
        'Por favor': 'Пожалуйста', Possível: 'Возможно'   , Praça   : 'Площадь'  , Prato : 'Тарелка'       , Precisar: 'Должен(а/о/ы)', 
        Preto      : 'Чёрный'    , Privada : 'Унитаз'     , Problema: 'Проблема' , Pronto: 'Готов'         , Proteger: 'Защищать'     , 
        Pescoço    : 'Шея'       , Pulso   : 'Запястье'   ,
    },
    Q: {
        Quadris: 'Бëдра'  , Quadro : 'Портрет', 'Quarta-feira': 'Среда' , Quatorze: 'Четырнадцать', Quatro        : 'Четыре' , Que: 'Что'          , 
        Quebrar: 'Сломать', Queijo : 'Сыр'    , Quem          : 'Кто'   , Querer  : 'Хотеть'      , 'Quinta-feira': 'Четверг', Quinze: 'Пятнадцать',
    },
    R: {
        Rainha : 'Королева'    , Rasgar  : 'Рвать'      , Rato     : 'Мышь'     , Realizar   : 'Выполнить', Realmente       : 'Действительно', 
        Receber: 'Получать'    , Reclamar: 'жаловаться' , Remédio  : 'Лекарство', Rei        : 'Король'   , Relatório       : 'Доклад'       , 
        Reserva: 'Бронирование', Reservar: 'Бронировать', Respeitar: 'Уважать'  , Restaurante: 'Ресторан' , Rodoviária      : 'Автовокзал'   , 
        Rosa   : 'Розовый'     , Roxo    : 'Фиолетовый' , Roubar   : 'Украсть'  , Roupas     : 'Одежда'   , 'Roupas íntimas': 'Трусы'        , 
        Russo  : 'Русский'     ,
    },
    S: {
        Saber       : 'Знать'      , Saia         : 'юбка'    , Sal       : 'Соль'     , Salada   : 'Салат'  , Sandálias      : 'Тапки'      ,
        Sauna       : 'Баня'       , Shorts       : 'Шорты'   , Sair      : 'Выйти'    , Sábado   : 'Суббота', 'Segunda-feira': 'Понедельник', 
        Sapatos     : 'Обувь'      , Saudade      : 'Тоска'   , Secretário: 'Секретарь', Selo     : 'Марка'  , Seis           : 'Шесть'      , 
        Sem         : 'Без'        , Senhor       : 'Господин', Senhora   : 'Госпожа'  , Ser      : 'Быть'   , Sete           : 'Семь'       , 
        Setembro    : 'Сентябрь'   , 'Sexta-feira': 'Пятница' , Sim       : 'Да'       , Sobremesa: 'Десерт' , Sonhar         : 'Мечтать'    ,
        Sopa        : 'Суп'        , Sorte        : 'Удача'   , Suco      : 'Сок'      , Suécia   : 'Швеция' , Suéter         : 'Свитер'     , 
        Supermercado: 'Супермаркет',
    },
    T: {
        Taça         : 'Бокал'    , Talvez     : 'Может быть', Também   : 'Тоже'    , Tamanho : 'Размер'    , Táxi       : 'Такси'         , 
        Tchau        : 'Пока пока', Teatro     : 'Театр'     , Telefone : 'Телефон' , Tênis   : 'Кроссовки' , Tentar     : 'Пробовать'     , 
        'Terça-feira': 'Вторник'  , Ter        : 'Иметь'     , Terno    : 'Костюм'  , Tocar   : 'Затронуть' , Todo       : 'Любой(inteiro)', 
        Tornozelo    : 'Лодыжка'  , Trabalhador: 'Рабочий'   , Trabalhar: 'Работать', Trabalho: 'Работа'    , Transportar: 'Водить'        ,
        Tratamento   : 'Лечение'  , Trem       : 'Поезд'     , Três     : 'Три'     , Treze   : 'Тринадцать', Trocar     : 'Заменить'      , 
        Tu           : 'Ты'       , Tudo       : 'Всё'       ,
    },
    U: {
        Ucrânia: 'Украина', Último: 'Последний', Um: 'Один', Uniforme: 'Форма', 'Um pouco': 'Немного', Urinar: 'Пописать', Usar: 'Использовать',
    },
    V: {
        Vaca         : 'Корова'        , Verificar: 'Проверить' , Velho            : 'Старый'       , Vender : 'Продать' , Verde : 'Зелёный' , 
        'Verde claro': 'Светло-зелёный', Vermelho : 'Красный'   , 'Vermelho escuro': 'Тёмно-красный', Vestido: 'Платье'  , Vestir: 'Надевать', 
        Vinho        : 'Вино'          , Visão    : 'Зрение'    , 'Video game'     : 'Видеоигра'    , Vinte  : 'Двадцать', Você  : 'Вы'      , 
        Vós          : 'Вы'            , Votar    : 'Голосовать',
    },
    X: {
        Xícara: 'Чашка',
    },
    Z: {
        Zero: 'Нуль',
    }
}