export default {
    A: {
        Abacate    : 'Авокадо'      , Abacaxi      : 'Ананас'       , Abaixo      : 'Под'       , Abaixar    : 'Опускать'  , Abandonar  : 'Оставлять',
        Aberto     : 'Открытый'     , Abismo       : 'Бездна'       , Abril       : 'Апрель'    , Acima      : 'Над'       , Acrescentar: 'Добавить' ,
        Adeus      : 'До свидания'  , Administrador: 'Администратор', Admitir     : 'Признать'  , Adoecer    : 'Заболеть'  , Adormecer  : 'Заснуть'  ,
        Adulto     : 'Взрослый'     , Aeroporto    : 'Аэропорт'     , Agosto      : 'Август'    , Agradecer  : 'Благдарить', Água       : 'Вода'     ,
        Ajuda      : 'Помощь'       , Alcançar     : 'Достать'      , Alegrar     : 'Радовать'  , Alegremente: 'Всело'     , Além       : 'Дальше'   ,
        Alemanha   : 'Германия'     , Alemão       : 'Немецкий'     , Algo        : 'Что-нибудь', Ali        : 'Там'       , Alimentar  : 'Кормить'  , 
        Alma       : 'Душа'         , Almoçar      : 'Обедать'      , Almoço      : 'Обед'      , Alto       : 'Высокий'   , Amanhã     : 'Завтра'   , 
        Amar       : 'Любить'       , Amarelo      : 'Жёлтый'       , Amigo       : 'Друг'      , Amizade    : 'Дружба'    , Amor       : 'Любовь'   , 
        Aniversário: 'День рождения', Anotar       : 'Записывать'   , Aparecer    : 'Появиться' , Aprender   : 'Учить'     , Aquele     : 'Тот'      , 
        Aqui       : 'Тут / здесь'  , Arremessar   : 'Бросить'      , Arroz       : 'Рис'       , Arquiteto  : 'Архитектор', Assim      : 'Так'      , 
        Assistir   : 'Смотреть'     , Assustado    : 'Страшно'      , Atacar      : 'Ударить'   , Atleta     : 'Спортсмен' , Avô        : 'Дедушка'  , 
        Avó        : 'Бабушка'      , Azul         : 'Синий'        , 'Azul claro': 'Голубой'   ,
    },
    B: {
        Baixo     : 'Короткий'  , Balançar: 'Качать'  , Banco : 'Банк'    , Banheiro  : 'Ванная комната'  , Banquisa  : 'Льдина'           ,
        Bar       : 'Бар'       , Bebida  : 'Напиток' , Barba : 'Борода'  , Barco     : 'Корабль'         , Básico    : 'Основной'         ,
        Bastante  : 'Достаточно', Batata  : 'Картошка', Bebê  : 'Младенец', Beber     : 'Пить'            , Bem       : 'Хорошо'           ,
        Biblioteca: 'Библиотека', Boca    : 'Рот'     , Bola  : 'Мяч'     , Bom       : 'Хороший'         , Bonito    : 'Красивый'         ,
        Botas     : 'Ботинки'   , Branco  : 'Белый'   , Brasil: 'Бразилия', Brasileiro: 'Бразилец (subst)', Brasileiro: 'бразильский (adj)',
        Buraco    : 'Дырка'     , Buscar  : 'Искать'  ,
    },
    C: {
        Cabeça   : 'Голова'    , Cabelo     : 'Волос'      , Caçar     : 'Ловить'     , Cachecol          : 'Шарф'         , Cachorro     : 'Собака'      ,
        Cadeira  : 'Стул'      , Café       : 'Кофе'       , Calor     : 'Тепло'      , Canadá            : 'Канада'       , Caneta       : 'Ручка'       ,
        Cansado  : 'томный'    , Chapéu     : 'Шляпа'      , Cair      : 'Выпасть'    , 'Caixa eletrônico': 'Банкомат'     , Cama         : 'Кровать'     ,
        Caminhar : 'Ходить'    , Cardápio   : 'Меню'       , Carne     : 'Мясо'       , 'Carne bovina'    : 'Говядина'     , 'Carne suína': 'Свинина'     ,
        Carro    : 'Машина'    , Carteira   : 'Бумажник'   , Casa      : 'Дом'        , Casaco            : 'Пальто'       , Catorze      : 'Четырнадцать',
        Cavalo   : 'Лошадь'    , Cazaquistão: 'Казахстан'  , Cebola    : 'Лук'        , Centro            : 'Центр'        , Certo        : 'Правильный'  , 
        Cerveja  : 'Пиво'      , Chá        : 'Чай'        , chão      : 'Пол'        , Chamada           : 'Вызов'        , Chamar       : 'Звать'       , 
        Chatear  : 'Наскучить' , Chorar     : 'Плакать'    , China     : 'Китай'      , Cidade            : 'Город'        , Cinco        : 'Пять'        , 
        Cinza    : 'Серый'     , Circo      : 'Цирк'       , Cliente   : 'Клиент'     , Cobrir            : 'Накрывать'    , Coisa        : 'Вещь'        , 
        Colar    : 'Клеить'    , Coleção    : 'Подборка'   , Colega    : 'Коллега'    , Colher            : 'Ложка (subst)', Comer        : 'Есть'        , 
        Combate  : 'бой'       , Comida     : 'Еда'        , Como      : 'Как'        , Complicado        : 'Сложный'      , Compra       : 'Покупка'     , 
        Comprar  : 'Купить'    , Confiar    : 'Доверять'   , Confundir : 'Спутать'    , Conhecer          : 'Встречать'    , Conseguir    : 'Достичь'     , 
        Congelar : 'Замерзнуть', Conjunto   : 'Набор'      , Considerar: 'Рассмотреть', Consumidor        : 'Покупатель'   , Conta        : 'Счёт'        , 
        Continuar: 'Продолжать', Contra     : 'Против'     , Copo      : 'Стакан'     , Cor               : 'Цвет'         , Coração      : 'Сердце'      , 
        Coreia   : 'Корея'     , Cortar     : 'Нарезать'   , Costas    : 'Спина'      , Costela           : 'Ребро'        , Cotovelo     : 'Локоть'      , 
        Cozinha  : 'Кухня'     , Cozinhar   : 'Приготовить', Crescer   : 'Расти'      , Criança           : 'Ребёнок'      , Crianças     : 'Дети'        , 
        Cume     : 'Вершина'   , Custar     : 'Стоить'     ,
    },
    D: { 
        Daqui     : 'Отсюда'       , De          : 'Из'           , Debaixo        : 'Под'        , Declarar : 'Заявить'    , Decidir  : 'Решать'     ,
        Decisão   : 'Решение'      , Dedo        : 'Палец'        , Definitivamente: 'Определённо', Delicioso: 'Вкусный'    , Demais   : 'Слишком'    , 
        'De fato' : 'Именно'       , 'De repente': 'Вдруг'        , 'De onde'      : 'Откуда'     , Depender : 'Зависеть'   , Derrotado: 'Побеждённый', 
        Descansar : 'Отдохнуть'    , Desgraça    : 'Бедa'         , Despedir       : 'Прощать'    , Dez      : 'Десять'     , Dezembro : 'Декабрь'    , 
        Dezoito   : 'Восемнадцать' ,  Dezenove   : 'Девятнадцать' , Dezesseis      : 'Шестнадцать', Dezessete: 'Семнадцать' , Dia      : 'День'       , 
        Dicionário: 'Словарь'      ,  Direito    : 'Правый (lado)', Discutir       : 'Обсудить'   , Dizer    : 'Сказать'    , Dois     : 'Два'        , 
        Doente    : 'Больной/болен',  Domingo    : 'Воскресенье'  , Doze           : 'Двенадцать' , Durante  : 'В течение'  ,
    },
    E: {
        E       : 'И'           , 'É claro' : 'Конечно'       , Economia    : 'Экономика', Egito  : 'Египет'   , Ela          : 'Она'        ,
        Ele     : 'Он'          , Eles      : 'Они'           , Em          : 'В / на'   , Encarar: 'Предстать', Endereço     : 'Адрес'      ,
        Então   : 'Тогда'       , Entender  : 'Понимать'      , Envergonhado: 'Стыдно'   , Errado : 'Неправый' , Escócia      : 'Шотландия'  , 
        Escola  : 'Школа'       , Escrever  : 'Писать'        , Escritório  : 'Офис'     , Escuro : 'Тёмный'   , Especialmente: 'Особенно'   , 
        Espelho : 'Зеркало'     , Esporte   : 'Спорт'         , Espanha     : 'Испания'  , Esposa : 'Жeнa'     , Esquecer     : 'Забыть'     , 
        Esquerdo: 'Левый (lado)', Estádio   : 'Стадион'       , Estação     : 'Станция'  , Estante: 'Шкаф'     , Este         : 'Этот'       , 
        Estômago: 'Желудок'     , Evidência : 'Доказательство', Evitar      : 'Избегать' , Eu     : 'Я'        , Examinar     : 'Осматривать',
        Estúpido: 'Глупый'      , Exatamente: 'Точно'         , Explicar    : 'Объяснять',   
    },
    F: {
        Fábrica: 'Завод'   , Faca      : 'Нож'        , Falar   : 'Говорить'  , Falsificação: 'подделка', Falso    : 'Неверный(ая)', Faminto: 'Голодный',
        Família: 'Семья'   , Fantástico: 'Потрясающий', Farmácia: 'Аптека'    , Favorito    : 'Любимый' , Fazenda  : 'Ферма'       , Fazer  : 'Делать'  ,
        Fechado: 'Закрытый', Feio      : 'Некрасивый' , Feliz   : 'Счастливый', Feminino    : 'Женский' , Fevereiro: 'Февраль'     , Ficar  : 'Остаться',
        Filha  : 'Дочь'    , Filho     : 'Сын'        , Fino    : 'Тонкий'    , Forte       : 'Сильный' , Fraco    : 'Слабый'      , França : 'Франция' ,
        Frango : 'Курица'  , Fruta     : 'Фрукт'      , Futuro  : 'Будущий'   ,
    },
    G: {
        Ganhar: 'Выиграть', Garçom        : 'Официант', Garçonete: 'Официантка' , Garfo : 'Вилка'  , Garganta: 'Горло/глотка', Garrafa: 'Бутылка' ,
        Garota: 'Девочка ', Garoto        : 'Мальчик ', Gato     : 'Кот / Кошка', Gênio : 'Гений'  , Gás     : 'Газ'         , Genitor: 'Родитель',
        Gordo : 'Толстый' , Gorro         : 'Шапка'   , Gostar   : 'Нравиться'  , Grande: 'Большой', Gramado : 'Газон'       , Gravata: 'Галстук' ,
        Grito : 'Крик'    , 'Guarda-chuva': 'Зонт'    ,
    },
    H: {
        Hoje: 'Сегодня', Homem: 'Мужчина', Hora: 'Час', Hospital: 'Больница'
    },
    I: {
        Imaginação : 'Воображение', Inglês : 'Английский', Índia: 'Индия' , Infecção: 'Инфекция', Inferno : 'Ад'  , Informar: 'Сообщить',
        Insanamente: 'Безумно'    , Injusto: 'Нечестный' , Irmã : 'Сестра', Irmão   : 'Брат'    , Irritado: 'Злой', Irritar : 'Бесить'  ,
        Isso       : 'Оно'        , Itália : 'Италия'    ,
    },
    J: {
        Janeiro: 'Январь', Jantar: 'Ужинать (verbo)', Jaqueta: 'Пиджак', Japão: 'Япония', Joelho: 'Колень', Jogo: 'Игра', Jogar: 'Играть',
        Jornal : 'Газета', Junho : 'Июнь'           , Julho  : 'Июль'  ,
    },
    L: {
        Lado : 'Сторона' , Laranja: 'Апельсин'  , Laranjado: 'Оранжевый'      , Largar  : 'Покидать', Legal: 'Классный', Legume: 'Овощ'   ,
        Leite: 'Молоко'  , Lembrar: 'Вспоминать', Lento    : 'медленный'      , Levantar: 'Вставать', Letra: 'Буква'   , Ler   : 'Читать' ,
        Ligar: 'Включать', Língua : 'Язык'      , Livraria : 'Книжный магазин', Livro   : 'Книга'   , Limão: 'Лимон'   , Longo : 'Длинный', 
        Loja : 'Магазин' , Luvas  : 'Перчатки'  ,
    },
    M: {
        Mãe     : 'Мать'      , Macarrão: 'Макароны'   , Maçã     : 'Яблоко'     , Magro      : 'Худой'   , Maio            : 'Май'    ,
        Maior   : 'Побольше'  , Manteiga: 'Масло'      , Março    : 'Март'       , Maravilhoso: 'Чудесный', Maravilhosamente: 'Чудесно',
        Marido  : 'Муж'       , Marrom  : 'Коричневый' , Masculino: 'Мужской'    , Matar      : 'Убить'   , Meias           : 'Носки'  ,
        Memória : 'Память'    , Melhor  : 'Лучший'     , Melhorar : 'Поправиться', Menor      : 'Поменьше', Mercado         : 'Рынок'  ,
        Merda   : 'Гавно(adj)', Mesa    : 'Стол'       , Mexer    : 'Двигаться'  , Molhado    : 'Мокрый'  , Molho           : 'Соус'   ,
        Montanha: 'Гора'      , Monótono: 'Монотонный' , Morador  : 'Житель'     , Mudar      : 'Изменить', Muito           : 'Очень'  , 
        Mulher  : 'Женщина'   ,
    },
    N: {
        Não         : 'Не / нет'   , Nada   : 'Ничего'        , Namorada    : 'Девушка'  , Nariz      : 'Нос'       , Nascimento :  'Рождение',
        Naturalmente: 'Естественно', Nativo : 'Местный'       , 'Na verdade': 'Вообще-то', Necessário : 'Необходимо', Neto       : 'Внучок'   ,
        Ninguém     : 'Никто'      , Nojento: 'Отвратительный', Nome        : 'Имя'      , Normal     : 'Нормально' , Normalmente: 'Обычно'   , 
        Noruega     : 'Норвегия'   , Nós    : 'Мы'            , Nove        : 'Девять'   , Novembro   : 'Ноябрь'    , Novo       : 'Новый'    , 
        Número      : 'Номер'      , 
    },
    O: {
        Obrigado: 'Спасибо', Observar: 'Наблюдать', Oferecer: 'Предложить', Oi  : 'Привет(informal)', Oito   : 'Восемь', Olho    : 'Глаз'     ,
        Onde    : 'Где'    , Ônibus  : 'Автобус'  , Ontem   : 'Вчера'     , Onze: 'Одиннадцать'     , Oops   : 'Ой'    , Opinar  : 'Высказать',
        Opinião : 'Мнение' , Ordem   : 'Приказ'   , Orelha  : 'Ухо'       , Ovo : 'Яйцо'            , Ou     : 'Или'   , Outubro : 'Октябрь'  ,
        Ombro   : 'Плечо'  ,
    },
    P: {
        Pão     : 'Хлеб'        , Pagar   : 'Платить'  , Pai      : 'Отец'     , Palavra : 'Слово'        , Parar      : 'Остановить(ся)',
        Papel   : 'Бумага'      , Parque  : 'Парк'     , Parte    : 'Часть'    , Pedir   : 'Заказывать'   , Pegar      : 'Брать'         ,
        Peito   : 'Грудь'       , Peixe   : 'Рыба'     , Pelado   : 'Голый'    , Pele    : 'Кожа'         , Pendurar   : 'висеть'        ,
        Pensar  : 'Думать'      , Perceber: 'Проводить', Perder   : 'Проиграть', Perfeito: 'Идеальный'    , Pergunta   : 'Вопрос'        ,
        Permitir: 'Пускать'     , Perna   : 'Нога'     , Pernoitar: 'Ночевать' , Perto   : 'Возле/Рядом'  , Pescador   : 'Рыбак'         ,
        Pessoa  : 'Человек'     , Pessoas : 'Люди'     , Pequeno  : 'Маленький', Pingar  :  'Капать'      , Piscina    : 'Бассейн'       ,
        Planejar: 'Собирать(ся)', Poeta   : 'Поэт'     , Ponte    : 'Мост'     , Por     : 'За'           , 'Por favor': 'Пожалуйста'    ,
        Possível: 'Возможно'    , Praça   : 'Площадь'  , Prato    : 'Тарелка'  , Precisar: 'Должен(а/о/ы)', Preto      : 'Чёрный'        ,
        Privada : 'Унитаз'      , Problema: 'Проблема' , Pronto   : 'Готов'    , Proteger: 'Защищать'     , Pescoço    : 'Шея'           ,
        Pulso   : 'Запястье'    ,     
    },
    Q: {
        Quadris       : 'Бëдра'  , Quadro : 'Портрет'   , Qualidade: 'Качество', 'Quarta-feira': 'Среда', Quatorze: 'Четырнадцать', Quatro: 'Четыре' ,
        Que           : 'Что'    , Quebrar: 'Сломать'   , Queijo   : 'Сыр'     , Quem          : 'Кто'  , Quente  : 'Тёплый'      , Querer: 'Хотеть' ,
        'Quinta-feira': 'Четверг', Quinze : 'Пятнадцать',
    },
    R: {
        Rainha   : 'Королева'     , Rasgar     : 'Рвать'     , Rato      : 'Мышь'        , Real            : 'Настоящий'   , Realizar : 'Выполнить',
        Realmente: 'Действительно', Receber    : 'Получать'  , Reclamar  : 'Жаловаться'  , Recusar         : 'Отказать(ся)', Remédio  : 'Лекарство',
        Rei      : 'Король'       , Relatório  : 'Доклад'    , Reserva   : 'Бронирование', Reservar        : 'Бронировать' , Respeitar: 'Уважать'  ,
        Revista  : 'Журнал'       , Restaurante: 'Ресторан'  , Rodoviária: 'Автовокзал'  , Rosa            : 'Розовый'     , Rosto    : 'Лиц'      ,
        Roxo     : 'Фиолетовый'   , Roubar     : 'Украсть'   , Roupas    : 'Одежда'      , 'Roupas íntimas': 'Трусы'       , Russo    : 'Русский'  ,
    },
    S: {
        Saber       : 'Знать'   , Saia         : 'юбка'       , Sal       : 'Соль'     , Salada   : 'Салат'  , Sandálias      : 'Тапки'      ,
        Sauna       : 'Баня'    , Shorts       : 'Шорты'      , Sair      : 'Выйти'    , Sábado   : 'Суббота', 'Segunda-feira': 'Понедельник',
        Sapatos     : 'Обувь'   , Saudade      : 'Тоска'      , Secretário: 'Секретарь', Selo     : 'Марка'  , Seis           : 'Шесть'      ,
        Sem         : 'Без'     , Senhor       : 'Господин'   , Senhora   : 'Госпожа'  , Ser      : 'Быть'   , Sete           : 'Семь'       ,
        Setembro    : 'Сентябрь', 'Sexta-feira': 'Пятница'    , Sim       : 'Да'       , Sobremesa: 'Десерт' , Sonhar         : 'Мечтать'    ,
        Sopa        : 'Суп'     , Soprar       : 'Веять'      , Sorte     : 'Удача'    , Suco     : 'Сок'    , Suécia         : 'Швеция'     ,
        Suéter      : 'Свитер'  , Supermercado : 'Супермаркет',
    },
    T: {
        Taça       : 'Бокал'         , Talvez       : 'Наверно' , Também     : 'Тоже'   , Tamanho  : 'Размер'  , Táxi    :   'Такси'    ,
        Tchau      : 'Пока пока'     , Teatro       : 'Театр'   , Telefone   : 'Телефон', Telhado  : 'Крыша'   , Tênis   :  'Кроссовки' ,
        Tentar     : 'Пробовать'     , 'Terça-feira': 'Вторник' , Ter        : 'Иметь'  , Terno    : 'Костюм'  , Tocar   : 'Затронуть'  ,
        Todo       : 'Любой(inteiro)', Tornozelo    : 'Лодыжка' , Trabalhador: 'Рабочий', Trabalhar: 'Работать', Trabalho: 'Работа'     ,
        Transportar: 'Водить'        , Tratamento   : 'Лечение' , Trem       : 'Поезд'  , Três     : 'Три'     , Treinar : 'Тренировать',
        Treze      : 'Тринадцать'    , Triste       : 'Грустный', Trocar     : 'Заменить', Tu      : 'Ты'      , Tudo    : 'Всё'        ,
    },
    U: {
        Ucrânia: 'Украина' , Último: 'Последний'   , Um: 'Один', Uniforme: 'Форма', Universidade: 'Университет', 'Um pouco': 'Немного',
        Urinar : 'Пописать', Usar  : 'Использовать',
    },
    V: {
        Vaca        : 'Корова'   , Verificar    : 'Проверить'     , Velho   : 'Старый' , Vender           : 'Продать'      , Ver       : 'Видеть'    ,
        Verde       : 'Зелёный'  ,'Verde claro' : 'Светло-зелёный', Vermelho: 'Красный', 'Vermelho escuro': 'Тёмно-красный', Vestido   : 'Платье'    ,
        Vestir      : 'Надевать' ,'Vice e versa': 'Наоборот'      , Vinho   : 'Вино'   , Visão            : 'Зрение'       ,'Visto que': 'Поскольку' ,
        'Video game': 'Видеоигра',  Vinte       : 'Двадцать'      , Você    : 'Вы'     , Vós              : 'Вы'           , Votar     : 'Голосовать',
        Voz         : 'Голос'    ,
    },
    X: {
        Xícara: 'Чашка',
    },
    Z: {
        Zero: 'Нуль',
    }
}